### ISSUE TITLE
Yaw -> roll

### ISSUE THREAD

**Issue by thijssteel** [p-en-o-cw-2016/p-en-o-cw-2016#1]
> Then, initially, and after each simulation step (i.e., after simulated time is advanced), the testbed sends the current drone sensor information, and the autopilot responds with the new motion parameters. Specifically, the testbed sends the following information, in the following order:
> 
> the left camera image
> the right camera image
> float pitch
> float yaw
> float currentTime (the amount of simulated time that has elapsed since the start of the simulation)

Shouldn't "yaw" be "roll"?

**Comment by btj** [comment]
Indeed. Thanks!
