### ISSUE TITLE
provided testbed loading error

### ISSUE THREAD

**Issue by AntoonDeCleen** [p-en-o-cw-2016/p-en-o-cw-2016#2]
Initiating the provided testbed with the .wdf file generated with  simple_example_world_description_file_builder.html creates two testbeds, one empty and one who disconnects a non-existing drone when the simulation is started. A new drone cannot be initialized via the wire after this. When no world file is loaded into the testbed, a drone can be initialized via wire. Tested on the lab computers.

**Comment by btj** [comment]
Please report issues with the provided testbed at https://github.com/p-en-o-cw-2016/testbed-provided .
